# Generated by Django 4.2.17 on 2025-12-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_color_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(db_index=True, default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference'], name='store_order_referen_2be885_idx'),
        ),
    ]
