# Generated by Django 4.2.17 on 2025-12-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('customer', 'Customer')], max_length=20)),
                ('actor_identifier', models.CharField(help_text='e.g. admin:5, system, customer:+8801XXXXXXX', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='store_produ_created_5555f3_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock'], name='store_produ_stock_675fe5_idx'),
        ),
        migrations.AddField(
            model_name='orderstatusauditlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='store.order'),
        ),
        migrations.AddIndex(
            model_name='orderstatusauditlog',
            index=models.Index(fields=['order'], name='store_order_order_i_82e535_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatusauditlog',
            index=models.Index(fields=['created_at'], name='store_order_created_10448b_idx'),
        ),
    ]
