# Generated by Django 4.2.17 on 2025-12-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderstatusauditlog_alter_order_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Displayed on landing page category cards only.', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='actor_identifier',
            field=models.CharField(help_text='e.g. admin:5, system, customer:+8801XXXXXXXXX', max_length=255),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='store_categ_parent__e56892_idx'),
        ),
    ]
