# Generated by Django 4.2.17 on 2026-01-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_campaign',
            field=models.BooleanField(default=False, help_text='Marks category as campaign (Sale, Mega Deals, Events)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Displayed on landing & campaign cards only', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order'),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='actor_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_campaign'], name='store_categ_is_camp_b278a3_idx'),
        ),
    ]
