# Generated by Django 4.2.17 on 2026-01-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_is_campaign_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Optional banner image', null=True, upload_to='campaigns/')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='store_categ_is_camp_b278a3_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_campaign',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Used on landing & campaign cards only', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (hierarchy)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='store.category'),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='actor_identifier',
            field=models.CharField(help_text='admin:5 | system | customer:+8801XXXXXXXXX', max_length=255),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['slug'], name='store_campa_slug_6ae694_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='store_campa_is_acti_4b74c6_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['starts_at'], name='store_campa_starts__adc897_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['ends_at'], name='store_campa_ends_at_196e0d_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='campaigns',
            field=models.ManyToManyField(blank=True, help_text='Sales / deals / events', related_name='products', to='store.campaign'),
        ),
    ]
