# Generated by Django 4.2.17 on 2026-01-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='campaigns',
        ),
        migrations.AddField(
            model_name='category',
            name='is_campaign',
            field=models.BooleanField(default=False, help_text='Marks this category as a sale / offer / event'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Used for landing cards & campaign banners only', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional strikethrough price for offers', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_campaign'], name='store_categ_is_camp_b278a3_idx'),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
