# Generated by Django 4.2.17 on 2026-01-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_campaigns_category_is_campaign_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('ordering', '-priority', 'name'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Campaign end time (optional)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority campaigns appear first'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_countdown',
            field=models.BooleanField(default=False, help_text='Frontend may show countdown timer'),
        ),
        migrations.AddField(
            model_name='category',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Campaign start time (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Used for landing cards & campaign banners', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_campaign',
            field=models.BooleanField(default=False, help_text='Marks this category as a campaign / sale / event'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Products may belong to multiple categories & campaigns', limit_choices_to={'is_active': True}, related_name='products', to='store.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['starts_at'], name='store_categ_starts__52226b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['ends_at'], name='store_categ_ends_at_5d4876_idx'),
        ),
    ]
