# Generated by Django 4.2.17 on 2026-01-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_category_options_category_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Used for landing cards & campaign visuals', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_campaign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_countdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='actor_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_desktop', models.ImageField(help_text='Large screens (≥1024px)', upload_to='banners/desktop/')),
                ('image_tablet', models.ImageField(help_text='Tablets & small laptops', upload_to='banners/tablet/')),
                ('image_mobile', models.ImageField(help_text='Mobile screens', upload_to='banners/mobile/')),
                ('is_active', models.BooleanField(default=True, help_text='Disable to hide banner without deleting')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Optional visibility start time', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Optional visibility end time', null=True)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority')),
            ],
            options={
                'ordering': ('ordering', 'id'),
                'indexes': [models.Index(fields=['is_active'], name='store_herob_is_acti_dc418a_idx'), models.Index(fields=['starts_at'], name='store_herob_starts__e7d476_idx'), models.Index(fields=['ends_at'], name='store_herob_ends_at_3c442e_idx')],
            },
        ),
    ]
