# Generated by Django 4.2.17 on 2026-01-02 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_category_ends_at_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ('ordering', '-created_at')},
        ),
        migrations.AddField(
            model_name='herobanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Used for stable ordering & auditing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Campaign end time', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_campaign',
            field=models.BooleanField(default=False, help_text='Marks this category as a campaign / offer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority appears first'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_countdown',
            field=models.BooleanField(default=False, help_text='Frontend may show countdown timer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Campaign start time', null=True),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='actor_identifier',
            field=models.CharField(help_text='admin:5 | system | customer:+8801XXXXXXXXX', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Products may belong to multiple categories & campaigns', limit_choices_to={'is_active': True}, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional strikethrough price', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['created_at'], name='store_herob_created_2d07b6_idx'),
        ),
    ]
