# Generated by Django 4.2.17 on 2026-01-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_herobanner_options_herobanner_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility without deleting')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower number = appears first')),
                ('seo_title', models.CharField(blank=True, help_text='Optional SEO title override for this menu item', max_length=255)),
                ('seo_description', models.CharField(blank=True, help_text='Optional SEO meta description override', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category to show in landing page body menu', on_delete=django.db.models.deletion.CASCADE, related_name='landing_menu_items', to='store.category')),
            ],
            options={
                'verbose_name': 'Landing Menu Item',
                'verbose_name_plural': 'Landing Menu Items',
                'ordering': ('ordering', 'id'),
                'indexes': [models.Index(fields=['is_active'], name='store_landi_is_acti_9e6b1b_idx'), models.Index(fields=['ordering'], name='store_landi_orderin_475c59_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='landingmenuitem',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_category_in_landing_menu'),
        ),
    ]
