# Generated by Django 4.2.17 on 2026-01-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_landingmenuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingmenuitem',
            name='category',
            field=models.ForeignKey(help_text='Category to show in landing page menu', on_delete=django.db.models.deletion.CASCADE, related_name='landing_menu_items', to='store.category'),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first'),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override', max_length=255),
        ),
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility without deleting')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='High-quality image for landing page. Recommended: square or portrait.', upload_to='featured-categories/')),
                ('category', models.ForeignKey(help_text='Category to feature on landing page', on_delete=django.db.models.deletion.CASCADE, related_name='featured_categories', to='store.category')),
            ],
            options={
                'verbose_name': 'Featured Category',
                'verbose_name_plural': 'Featured Categories',
                'ordering': ('ordering', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='store_featu_is_acti_984058_idx'), models.Index(fields=['ordering'], name='store_featu_orderin_0df6a7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='featuredcategory',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_featured_category'),
        ),
    ]
