# Generated by Django 4.2.17 on 2026-01-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_landingmenuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcategory',
            name='category',
            field=models.ForeignKey(help_text='Category to feature on landing page.', on_delete=django.db.models.deletion.CASCADE, related_name='featured_categories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='featuredcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle visibility without deleting the item.'),
        ),
        migrations.AlterField(
            model_name='featuredcategory',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first.'),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='category',
            field=models.ForeignKey(help_text='Category to show in landing page menu.', on_delete=django.db.models.deletion.CASCADE, related_name='landing_menu_items', to='store.category'),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle visibility without deleting the item.'),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first.'),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Optional SEO meta description override.', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO title override for this menu item.', max_length=255),
        ),
        migrations.CreateModel(
            name='HotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility without deleting the item.')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower number appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Promotional lifestyle image for landing page. Recommended: wide / cinematic.', upload_to='hot-categories/')),
                ('category', models.ForeignKey(help_text='Category marked as hot for landing page.', on_delete=django.db.models.deletion.CASCADE, related_name='hot_categories', to='store.category')),
            ],
            options={
                'verbose_name': 'Hot Category',
                'verbose_name_plural': 'Hot Categories',
                'ordering': ('ordering', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='store_hotca_is_acti_39e18f_idx'), models.Index(fields=['ordering'], name='store_hotca_orderin_8254cc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hotcategory',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_hot_category'),
        ),
    ]
