# Generated by Django 4.2.17 on 2026-01-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_featuredcategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortCategoryRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_fill', models.BooleanField(default=True, help_text='Auto-pick products if none selected')),
                ('auto_limit', models.PositiveIntegerField(default=8, help_text='How many products to show')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Category shown on the left', on_delete=django.db.models.deletion.CASCADE, related_name='comfort_rails', to='store.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Optional: manually selected products', related_name='comfort_rails', to='store.product')),
            ],
            options={
                'verbose_name': 'Comfort Section',
                'verbose_name_plural': 'Comfort Sections',
                'ordering': ('ordering', 'id'),
            },
        ),
    ]
