# Generated by Django 4.2.17 on 2026-01-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_comfortcategoryrail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('featured_categories', 'Featured Categories'), ('hot_categories', 'Hot Categories'), ('comfort_rail', 'Comfort Rail')], max_length=50)),
                ('title', models.CharField(blank=True, help_text='Internal label for admins only', max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear higher on the landing page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('products', models.ManyToManyField(blank=True, to='store.product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
