# Generated by Django 4.2.17 on 2026-01-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_landingblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingblock',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Used by Hot Categories & Comfort Rail', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = higher on landing page'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Optional. If empty → frontend auto-selects products.', to='store.product'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='title',
            field=models.CharField(blank=True, help_text='Internal label for admins (not shown on frontend)', max_length=120),
        ),
    ]
