# Generated by Django 4.2.17 on 2026-01-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_landingblock_category_alter_landingblock_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingblock',
            options={'ordering': ('ordering', 'id'), 'verbose_name': 'Landing Block', 'verbose_name_plural': 'Landing Blocks'},
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='order',
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='products',
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='title',
        ),
        migrations.RemoveField(
            model_name='landingblock',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='landingblock',
            name='comfort_rail',
            field=models.ForeignKey(blank=True, help_text='Used only when block type = Comfort Rail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.comfortcategoryrail'),
        ),
        migrations.AddField(
            model_name='landingblock',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='auto_fill',
            field=models.BooleanField(default=True, help_text='If enabled, auto-pick products from the category when none are selected'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='auto_limit',
            field=models.PositiveIntegerField(default=6, help_text='Maximum number of products to show in this rail'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='category',
            field=models.ForeignKey(help_text='Category shown on the left side of the comfort section', on_delete=django.db.models.deletion.CASCADE, related_name='comfort_rails', to='store.category'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls visibility on the landing page'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Optional: manually selected products (overrides auto-fill)', related_name='comfort_rails', to='store.product'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('featured', 'Featured Categories'), ('hot', 'Hot Categories'), ('comfort', 'Comfort Rail')], max_length=32),
        ),
    ]
