# Generated by Django 4.2.17 on 2026-01-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_landingblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('featured', 'Featured Categories'), ('hot', 'Hot Categories'), ('comfort_rail', 'Comfort Rail')], help_text='What type of block this is', max_length=32),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='comfort_rail',
            field=models.ForeignKey(blank=True, help_text='Required only when block type = Comfort Rail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_blocks', to='store.comfortcategoryrail'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable without deleting'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Controls vertical order on landing page'),
        ),
    ]
