# Generated by Django 4.2.17 on 2026-01-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_landingblock_block_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('menu', 'Landing Menu'), ('featured', 'Featured Categories'), ('hot', 'Hot Categories'), ('comfort_rail', 'Comfort Rail')], db_index=True, help_text='Type of block to render on landing page', max_length=32),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='comfort_rail',
            field=models.ForeignKey(blank=True, help_text="Required only when block type is 'Comfort Rail'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.comfortcategoryrail'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily hide this block'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the page'),
        ),
    ]
