# Generated by Django 4.2.17 on 2026-01-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_landingblock_block_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('menu', 'Landing Menu'), ('featured', 'Featured Categories'), ('hot', 'Hot Categories'), ('comfort_block', 'Comfort Editorial Block'), ('comfort_rail', 'Comfort Rail')], db_index=True, help_text='Type of block to render on landing page', max_length=32),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='comfort_rail',
            field=models.ForeignKey(blank=True, help_text="Required ONLY when block type is 'Comfort Rail'. Ignored for all other block types.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.comfortcategoryrail'),
        ),
    ]
