# Generated by Django 4.2.17 on 2026-01-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_landingblock_block_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingblock',
            name='hot_category',
            field=models.ForeignKey(blank=True, help_text="Required ONLY when block type is 'Hot Categories'. Ignored for all other block types.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.hotcategory'),
        ),
    ]
