# Generated by Django 4.2.17 on 2026-01-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_landingblock_block_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotCategoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility without deleting the item.')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower number appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional internal title for CMS identification.', max_length=255)),
            ],
            options={
                'verbose_name': 'Hot Category Block',
                'verbose_name_plural': 'Hot Category Blocks',
                'ordering': ('ordering', 'id'),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='featuredcategory',
            name='image',
            field=models.ImageField(help_text='High-quality image for landing page.', upload_to='featured-categories/'),
        ),
        migrations.AlterField(
            model_name='hotcategory',
            name='image',
            field=models.ImageField(help_text='Promotional image for landing page.', upload_to='hot-categories/'),
        ),
        migrations.CreateModel(
            name='HotCategoryBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Order inside the hot category block.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility inside the block.')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.hotcategoryblock')),
                ('hot_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_items', to='store.hotcategory')),
            ],
            options={
                'verbose_name': 'Hot Category Block Item',
                'verbose_name_plural': 'Hot Category Block Items',
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='hotcategoryblock',
            index=models.Index(fields=['is_active'], name='store_hotca_is_acti_02e3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='hotcategoryblock',
            index=models.Index(fields=['ordering'], name='store_hotca_orderin_12d290_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotcategoryblockitem',
            constraint=models.UniqueConstraint(fields=('block', 'hot_category'), name='unique_hot_category_per_block'),
        ),
    ]
