# Generated by Django 4.2.17 on 2026-01-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_hotcategoryblock_alter_featuredcategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingblock',
            name='hot_category',
        ),
        migrations.AddField(
            model_name='landingblock',
            name='hot_category_block',
            field=models.ForeignKey(blank=True, help_text="Required ONLY when block type is 'hot'. Must be empty for all other block types.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.hotcategoryblock'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('menu', 'Landing Menu'), ('featured', 'Featured Categories'), ('hot', 'Hot Categories Block'), ('comfort_block', 'Comfort Editorial Block'), ('comfort_rail', 'Comfort Rail')], db_index=True, help_text='Type of block to render on landing page', max_length=32),
        ),
    ]
