# Generated by Django 4.2.17 on 2026-01-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_landingblock_hot_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredcategory',
            options={'ordering': ('ordering', 'id')},
        ),
        migrations.AlterModelOptions(
            name='hotcategory',
            options={'ordering': ('ordering', 'id')},
        ),
        migrations.AlterModelOptions(
            name='landingmenuitem',
            options={'ordering': ('ordering', 'id')},
        ),
        migrations.AlterField(
            model_name='featuredcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_categories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='featuredcategory',
            name='image',
            field=models.ImageField(upload_to='featured-categories/'),
        ),
        migrations.AlterField(
            model_name='hotcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_categories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='hotcategory',
            name='image',
            field=models.ImageField(upload_to='hot-categories/'),
        ),
        migrations.AlterField(
            model_name='hotcategoryblock',
            name='title',
            field=models.CharField(blank=True, help_text='Internal CMS title (optional).', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotcategoryblockitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotcategoryblockitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_menu_items', to='store.category'),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='landingmenuitem',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
