# Generated by Django 4.2.17 on 2026-01-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_featuredcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Example: Fabric type, GSM, Composition', max_length=100)),
                ('value', models.CharField(help_text='Example: Double PK, 210-220, 80% Cotton', max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.product')),
            ],
            options={
                'ordering': ('ordering', 'id'),
                'unique_together': {('product', 'key')},
            },
        ),
    ]
