# Generated by Django 4.2.17 on 2026-01-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_productattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('ordering', 'name'), 'verbose_name': 'Product Attribute', 'verbose_name_plural': 'Product Attributes'},
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name',
            field=models.CharField(default='legacy', help_text='Attribute name (e.g. Fabric, GSM, Fit)', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short marketing description shown near title', max_length=255),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order globally'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='key',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Value (e.g. 100% Cotton, 180 GSM)', max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Controls order inside product page')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attribute Values',
                'ordering': ('ordering', 'id'),
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
