# Generated by Django 4.2.17 on 2026-01-11 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatusauditlog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='orderstatusauditlog',
            name='store_order_order_i_82e535_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderstatusauditlog',
            name='store_order_created_10448b_idx',
        ),
        migrations.RemoveField(
            model_name='orderstatusauditlog',
            name='actor_identifier',
        ),
        migrations.RemoveField(
            model_name='orderstatusauditlog',
            name='actor_type',
        ),
        migrations.RemoveField(
            model_name='orderstatusauditlog',
            name='from_status',
        ),
        migrations.RemoveField(
            model_name='orderstatusauditlog',
            name='to_status',
        ),
        migrations.AddField(
            model_name='orderstatusauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatusauditlog',
            name='new_status',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatusauditlog',
            name='previous_status',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Final payable amount including all charges', max_digits=10),
        ),
    ]
