# Generated by Django 4.2.17 on 2026-01-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_orderstatusauditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatusauditlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order Status Audit Log', 'verbose_name_plural': 'Order Status Audit Logs'},
        ),
        migrations.RemoveField(
            model_name='orderstatusauditlog',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='orderstatusauditlog',
            name='actor_identifier',
            field=models.CharField(default='pending', help_text='Identifier of the actor (e.g. admin:1, system, pathao:webhook)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatusauditlog',
            name='actor_type',
            field=models.CharField(default='pending', help_text='Who performed the action (admin, system, courier, etc.)', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='new_status',
            field=models.CharField(help_text='New order status after transition', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_audit_logs', to='store.order'),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='previous_status',
            field=models.CharField(blank=True, help_text='Previous order status (null for creation)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='orderstatusauditlog',
            index=models.Index(fields=['order', 'created_at'], name='store_order_order_i_ebae5a_idx'),
        ),
    ]
