# Generated by Django 4.2.17 on 2026-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(db_index=True, editable=False, help_text='Human-friendly order reference', max_length=20, unique=True),
        ),
    ]
