# Generated by Django 4.2.17 on 2026-01-12 16:22

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_order_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['ordering', 'id']},
        ),

        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(
                max_length=255,
                blank=True,
            ),
        ),

        # ✅ FIXED: correct callable default
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(
                default=timezone.now,
                editable=False,
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(
                default=False,
                help_text='Primary image used as main product image',
            ),
        ),

        migrations.AddField(
            model_name='productimage',
            name='ordering',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Lower number = shown first',
            ),
        ),

        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                help_text='Products may belong to multiple categories & campaigns',
                limit_choices_to={'is_active': True},
                related_name='products',
                to='store.category',
            ),
        ),

        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(
                upload_to='products/',
                blank=True,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(
                upload_to='product_images/',
            ),
        ),

        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(
                fields=['product', 'is_primary'],
                name='store_produ_product_e3fa15_idx',
            ),
        ),
    ]
