# Generated by Django 4.2.17 on 2026-01-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_productimage_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Products may belong to multiple categories', limit_choices_to={'is_active': True}, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short marketing description', max_length=255),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(help_text='Attribute name (e.g. Fabric, GSM, Fit)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Global display order'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='store.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Display order within product page'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['ordering'], name='store_produ_orderin_b6340b_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['name'], name='store_produ_name_75a73e_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['product'], name='store_produ_product_37cb52_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute'], name='store_produ_attribu_17d83a_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['ordering'], name='store_produ_orderin_93addc_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('name', ''), _negated=True), fields=('name',), name='unique_product_attribute_name_ci'),
        ),
    ]
