# Generated by Django 4.2.17 on 2026-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_product_categories_alter_product_old_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='unique_product_attribute_name_ci',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive categories are hidden everywhere'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Display name of the category', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Sibling ordering (lower comes first)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Unique URL slug', unique=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(help_text='Attribute name (e.g. Fabric, GSM, Fit)', max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
    ]
