# Generated by Django 4.2.17 on 2026-01-27 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_productattribute_unique_product_attribute_name_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfortcategoryrail',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='MANDATORY image for this comfort rail (used on landing page)', upload_to='comfort_rails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Campaign end time (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Campaign start time (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='auto_fill',
            field=models.BooleanField(default=True, help_text='Automatically pick products from the category when no manual products are set'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='category',
            field=models.ForeignKey(help_text='Primary category represented by this comfort rail', on_delete=django.db.models.deletion.CASCADE, related_name='comfort_rails', to='store.category'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether this rail appears on the landing page'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear earlier on the landing page'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Optional manually selected products. If empty and auto_fill is enabled, products are auto-picked from category.', related_name='comfort_rails', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='comfortcategoryrail',
            index=models.Index(fields=['is_active', 'ordering'], name='store_comfo_is_acti_2f1f66_idx'),
        ),
        migrations.AddIndex(
            model_name='comfortcategoryrail',
            index=models.Index(fields=['category'], name='store_comfo_categor_b3ee80_idx'),
        ),
    ]
