# Generated by Django 4.2.17 on 2026-01-27 07:10

from django.db import migrations, models
import store.models.landing_comfort


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_comfortcategoryrail_image_alter_category_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='auto_fill',
            field=models.BooleanField(default=True, help_text='Auto-pick products from category when no manual products exist'),
        ),
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='image',
            field=models.ImageField(help_text='MANDATORY image for this comfort rail (landing page visual)', upload_to=store.models.landing_comfort.comfort_rail_image_path),
        ),
    ]
