# Generated by Django 4.2.17 on 2026-01-29 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_comfortcategoryrail_auto_fill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive attributes are archived (not deletable)'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['is_active'], name='store_produ_is_acti_ac517e_idx'),
        ),
    ]
