# Generated by Django 4.2.17 on 2026-01-30 15:27

from django.db import migrations, models
import store.models.landing_comfort_editorial


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_productattribute_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortEditorialBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Primary heading text', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Optional supporting description text')),
                ('image', models.ImageField(help_text='Required editorial image', upload_to=store.models.landing_comfort_editorial.comfort_editorial_image_path)),
                ('cta_text', models.CharField(blank=True, help_text='Optional CTA button text (e.g. Shop Now)', max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Optional CTA link (absolute or relative URL)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility without deleting')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comfort Editorial Block',
                'verbose_name_plural': 'Comfort Editorial Blocks',
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='SOFT DELETE FLAG — inactive categories do not exist publicly'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parent', 'name'), name='unique_active_category_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='comforteditorialblock',
            index=models.Index(fields=['is_active', 'ordering'], name='store_comfo_is_acti_aefa1c_idx'),
        ),
    ]
