# Generated by Django 4.2.17 on 2026-01-30 15:53

from django.db import migrations, models
import django.db.models.deletion
import store.models.landing_comfort_editorial


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_comforteditorialblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingblock',
            name='comfort_editorial_block',
            field=models.ForeignKey(blank=True, help_text="Required ONLY when block type is 'comfort_block'. Must be empty for all other block types.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.comforteditorialblock'),
        ),
        migrations.AlterField(
            model_name='comforteditorialblock',
            name='cta_text',
            field=models.CharField(blank=True, help_text="CTA button text (e.g. 'Explore Collection')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comforteditorialblock',
            name='cta_url',
            field=models.CharField(blank=True, help_text='CTA destination URL (absolute or relative)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comforteditorialblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional editorial image (recommended high quality)', null=True, upload_to=store.models.landing_comfort_editorial.comfort_editorial_image_path),
        ),
        migrations.AlterField(
            model_name='comforteditorialblock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle visibility without deleting the block'),
        ),
        migrations.AlterField(
            model_name='comforteditorialblock',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear earlier in CMS listings'),
        ),
        migrations.AlterField(
            model_name='comforteditorialblock',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Optional supporting text (short paragraph)', null=True),
        ),
        migrations.AlterField(
            model_name='comforteditorialblock',
            name='title',
            field=models.CharField(help_text='Main headline text for the editorial block', max_length=255),
        ),
    ]
