# Generated by Django 4.2.17 on 2026-01-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_landingblock_comfort_editorial_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('menu', 'Landing Menu'), ('featured', 'Featured Categories'), ('hot', 'Hot Categories Block'), ('comfort_block', 'Comfort Editorial Block'), ('comfort_rail', 'Comfort Rail')], db_index=True, help_text='Which block to render on the landing page', max_length=32),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='comfort_editorial_block',
            field=models.ForeignKey(blank=True, help_text="Required ONLY when block type is 'comfort_block'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.comforteditorialblock'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='comfort_rail',
            field=models.ForeignKey(blank=True, help_text="Required ONLY when block type is 'comfort_rail'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.comfortcategoryrail'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='hot_category_block',
            field=models.ForeignKey(blank=True, help_text="Required ONLY when block type is 'hot'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='store.hotcategoryblock'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Temporarily hide this block without deleting'),
        ),
        migrations.AlterField(
            model_name='landingblock',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddIndex(
            model_name='landingblock',
            index=models.Index(fields=['is_active', 'ordering'], name='store_landi_is_acti_68234a_idx'),
        ),
        migrations.AddIndex(
            model_name='landingblock',
            index=models.Index(fields=['block_type'], name='store_landi_block_t_756113_idx'),
        ),
    ]
