# Generated by Django 4.2.17 on 2026-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_landingblock_block_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfortcategoryrail',
            name='auto_limit',
            field=models.PositiveIntegerField(default=8, help_text='Maximum number of products to show in this rail'),
        ),
    ]
