# Generated by Django 4.2.17 on 2026-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_order_delivery_area_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Dhaka', max_length=120),
            preserve_default=False,
        ),
    ]
