# Generated by Django 4.2.17 on 2026-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0050_alter_productattributevalue_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="color_hex",
            field=models.CharField(
                max_length=7,
                blank=True,
                default="",
                help_text="Optional hex color code like #RRGGBB (used for color swatch on site).",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["color_hex"],
                name="store_produ_color_h_da4447_idx",
            ),
        ),
    ]